spring:
  application:
    name: BackendDeveloperTask

  datasource:
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:5432/ecommerce_db
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
        connection:
          release_mode: on_close

  cloudinary:
    cloud-name: drwwgagjj
    api-key: 955757652539184
    api-secret: iKNxSLdUW3Tqyn7ZQk56UzmdNiY

  data:
    redis:
      host: redis
      port: 6379
